baseURL = "http://fromzerotohugo.davidbeck.online/"
languageCode = "en-us"
title = "From Zero to Hugo - with AWS"

theme = "hugo-theme-learn"
uglyurls = true


sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"


[params]
  description = "Documentation on how to setup a static website on AWS with Hugo"
  author = "David Beck"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  titleSeparator = "::"